# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3956277aebab17b1c0600f9e3e2f3dc3a532fcdea0298d0650e421d329c5a12a525e2b0d639efa1f2c6103d333e28911f5231b91303966365015e0fe6f4a3938

test:
  secret_key_base: 72fb763405895e84dc03a92c088b658b551ddf698b98af1a5f88e7d94394663908228042cdd021adc40b7db0bd433875c85b4b7907e1a1a08d325171f94e2f89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
